### ISSUE TITLE
Errors in running Spartan Plugin with latest update (on stable branch)

### ISSUE THREAD

**Issue by M4tt30rru** [SpartanRefactoring/spartan-refactoring#49]
I am experiencing some errors that during the build of the application, namely after running "Run as application" with the latest udpate (commit 38acb5cb7a319f92c167e8f9f1f047e2fd0473fd).

The error is the following.

Errors running builder 'Spartanization Checker' on project 'mina-parent'.
Could not initialize class il.org.spartan.refactoring.spartanizations.Spartanizations.

The program throws the following Exception (taken from the console):

!MESSAGE Errors running builder 'Spartanization Checker' on project 'mina-benchmarks-common'.
!STACK 0
java.lang.ExceptionInInitializerError
	at il.org.spartan.refactoring.builder.Builder.addMarkers(Builder.java:57)
	at il.org.spartan.refactoring.builder.Builder.addMarkers(Builder.java:72)
	at il.org.spartan.refactoring.builder.Builder.lambda$1(Builder.java:110)
	at org.eclipse.core.internal.resources.Resource$2.visit(Resource.java:119)
	at org.eclipse.core.internal.resources.Resource$1.visitElement(Resource.java:83)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:82)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:129)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:93)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:51)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:116)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:104)
	at il.org.spartan.refactoring.builder.Builder.fullBuild(Builder.java:109)
	at il.org.spartan.refactoring.builder.Builder.build(Builder.java:90)
	at il.org.spartan.refactoring.builder.Builder.build(Builder.java:102)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.NullPointerException
	at il.org.spartan.refactoring.spartanizations.Spartanizations$1.<init>(Spartanizations.java:67)
	at il.org.spartan.refactoring.spartanizations.Spartanizations.<clinit>(Spartanizations.java:64)
	... 34 more

When trying to enable the Spartanization suggestions (by toggling on the corresponding item on the project's menu) it throws the following Exception

java.lang.NoClassDefFoundError: il/org/spartan/Utils
	at il.org.spartan.refactoring.handlers.ToggleSpartanizationHandler.enableNature(ToggleSpartanizationHandler.java:36)
	at il.org.spartan.refactoring.handlers.ToggleSpartanizationHandler.toggleNature(ToggleSpartanizationHandler.java:57)
	at il.org.spartan.refactoring.handlers.ToggleSpartanizationHandler.execute(ToggleSpartanizationHandler.java:44)
	at il.org.spartan.refactoring.handlers.ToggleSpartanizationHandler.execute(ToggleSpartanizationHandler.java:64)
	at il.org.spartan.refactoring.handlers.ToggleSpartanizationHandler.execute(ToggleSpartanizationHandler.java:1)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:252)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:493)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:486)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:799)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.handleWidgetSelection(HandledContributionItem.java:675)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.access$7(HandledContributionItem.java:659)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem$4.handleEvent(HandledContributionItem.java:592)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4481)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1329)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3819)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3430)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
Caused by: java.lang.ClassNotFoundException: il.org.spartan.Utils cannot be found by il.org.spartan.refactoring_2.5.0
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:439)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 50 more

It did not happen before.
If I reset to the commit 30a65bd02c737642fc7ca540229ce59683abc546 it works fine - I choose this commit because I remember that it was working fine since then.

Configurations:

On my laptop:

Eclipse Mars.2 Release (4.5.2)
JDK version "1.8.0_91"
Ubuntu 14.04

On the workstation

Eclipse Neon 4.6.0
JDK version "1.8.0_91"
Ubuntu Mate 16.04

**Comment by OriRoth** [comment]
Do you still having problems? There were some issues but the last version should be clean. If you get exceptions I believe *DELETING FROM DISK* + *REINSTALL FROM GIT* should solve it. Also help Yossi on his machine and close the issue when finishing. I will not be available during the next month.
